- python/graph_analyzer.py
- python/mgp_networkx.py
- python/nxalg.py
- python/wcc.py
> Add initial python modules

- python/distance_calculator.py
- python/set_cover.py
- python/tsp.py
For now, everything is in its own file and distance is duplicated in the tsp query module. When structure is complete, it will be separated into different files
> Added tsp, setcover and distance

- CONTRIBUTING.md
- README.md
> Update documentation links

- cpp/connectivity_module/connectivity_module.cpp
- e2e/weakly_connected_components_test/test_empty/test.yml
- e2e/weakly_connected_components_test/test_single_component/input.cyp
- e2e/weakly_connected_components_test/test_single_component/test.yml
- e2e/weakly_connected_components_test/test_two_components/input.cyp
- e2e/weakly_connected_components_test/test_two_components/test.yml
> Fix and test weakly connected components

- e2e/test_module.py
- python/tests/requirements.txt
- test_e2e
kudos to @antaljanosbenjamin for assembling `pymgclient`
> Add error margin to e2e tests. Remove Neo4j client

- README.md
- cpp/uuid_module/CMakeLists.txt
- cpp/uuid_module/uuid_module.cpp
- e2e/uuid_test/test_generation/test.yml
Closes this: https://discourse.memgraph.com/t/unable-to-setup-spacy-language-model-on-top-of-memgraph-mage/181
> Change UUID module name to uuid_generator.get()

- .dockerignore
- .github/workflows/test.yml
- Dockerfile
- README.md
- python/requirements.txt
- setup
Goal of this PR is to solve following issues:
Closes  #64
> Reduce docker image size, add black-box script for Docker

- .github/workflows/docker_publish.yml
Fix the workflow in order to create new releases automatically
> Fix release file

- e2e/test_module.py
Fix the E2E test to not shut down the connection once failed.
> Fix E2E testing  

- python/mage/geography/distance_calculator.py
- python/tests/requirements.txt
Change Black formatter version to latest stable 22.3.0
> Bump the version of Black formatter

- .github/workflows/docker_publish.yml
Bump up memgraph version to 2.4.1
> Update Memgraph version

- README.md
> [main < readme_update] Updated git clone to git clone --recurse-submodules

- cpp/map_module/algorithm/map.cpp
- cpp/map_module/algorithm/map.hpp
- cpp/map_module/map_module.cpp
- e2e/map_test/test_merge/test.yml
- e2e/map_test/test_merge_duplicate_key/test.yml
- e2e/map_test/test_merge_empty/test.yml
Implemented map.merge procedure and e2e tests for it
> [E-idora < T394] Implement merge for maps

- cpp/map_module/CMakeLists.txt
- cpp/map_module/algorithm/map.cpp
- cpp/map_module/algorithm/map.hpp
- cpp/map_module/map_module.cpp
- e2e/map_test/test_fromPairs_diff_types/test.yml
- e2e/map_test/test_fromPairs_key_dupl/test.yml
- e2e/map_test/test_fromPairs_key_not_str/test.yml
- e2e/map_test/test_fromPairs_not_pairs/test.yml
- e2e/map_test/test_merge/test.yml
- e2e/map_test/test_merge_duplicate_key/test.yml
- e2e/map_test/test_merge_empty/test.yml
- e2e/map_test/test_removeKey_exists/test.yml
- e2e/map_test/test_removeKey_not_exist/test.yml
- e2e/map_test/test_removeKey_recursion/test.yml
- e2e/map_test/test_removeKey_wrong_recursion/test.yml
Merged all mine map procedures.
- [x ] Code style update (formatting, renaming)
> [E-add-map-functions < E-idora] Merge all map implementations part 1

- cpp/map_module/algorithm/map.cpp
- cpp/map_module/algorithm/map.hpp
- cpp/map_module/map_module.cpp
- e2e/map_test/test_flatten1/test.yml
- e2e/map_test/test_flatten2/test.yml
- e2e/map_test/test_flatten3/test.yml
> [E-matija < T395] implement flatten function on maps

- e2e/test_module.py
Enabled testing paths and relationships in E2E tests
> [main < T611] Add testing paths and relationships in e2e

- .gitmodules
- cpp/util_module/CMakeLists.txt
- cpp/util_module/algorithm/md5.cpp
- cpp/util_module/algorithm/md5.hpp
- cpp/util_module/algorithm/util.cpp
- cpp/util_module/algorithm/util.hpp
- cpp/util_module/util_module.cpp
- e2e/util_module_online_test/test_online_util1/input.cyp
- e2e/util_module_online_test/test_online_util1/test.yml
- e2e/util_module_test/util_test1/test.yml
- e2e/util_module_test/util_test2/test.yml
- e2e/util_module_test/util_test3/test.yml
> [E-util < T580] Implement util.md5

- cpp/nodes_module/algorithm/nodes.cpp
- cpp/nodes_module/algorithm/nodes.hpp
- cpp/nodes_module/nodes_module.cpp
- e2e_correctness/nodes_test/test_delete_id/input.cyp
- e2e_correctness/nodes_test/test_delete_id/test.yml
- e2e_correctness/nodes_test/test_delete_ids/input.cyp
- e2e_correctness/nodes_test/test_delete_ids/test.yml
- e2e_correctness/nodes_test/test_delete_node/input.cyp
- e2e_correctness/nodes_test/test_delete_node/test.yml
- e2e_correctness/nodes_test/test_delete_nodes/input.cyp
- e2e_correctness/nodes_test/test_delete_nodes/test.yml
> [E-nodes < T478] Implement nodes.delete

- cpp/neighbors_module/algorithm/neighbors.cpp
- cpp/neighbors_module/algorithm/neighbors.hpp
- cpp/neighbors_module/neighbors_module.cpp
- e2e/neighbors_test/test_byhop/input.cyp
- e2e/neighbors_test/test_byhop/test.yml
- e2e/neighbors_test/test_byhop_direction/input.cyp
- e2e/neighbors_test/test_byhop_direction/test.yml
- e2e/neighbors_test/test_byhop_multiple/input.cyp
- e2e/neighbors_test/test_byhop_multiple/test.yml
Implemented neighbors.by_hop procedure
> [E-neighbors < T485] Implement byhop procedure

- cpp/node_module/algorithm/node.cpp
- cpp/node_module/algorithm/node.hpp
- cpp/node_module/node_module.cpp
- e2e/node_test/test_relationshipsExist1/input.cyp
- e2e/node_test/test_relationshipsExist1/test.yml
- e2e/node_test/test_relationshipsExist2/input.cyp
- e2e/node_test/test_relationshipsExist2/test.yml
- e2e/node_test/test_relationshipsExist3/input.cyp
- e2e/node_test/test_relationshipsExist3/test.yml
> [E-node < T499] Implement node.relationshipsExist

- python/mgps.py
Add mgps module and procedure components.
> [E-graphQL < T653] Add mgps module

- cpp/create_module/algorithm/create.hpp
- cpp/create_module/create_module.cpp
- cpp/label_module/algorithm/label.cpp
- cpp/label_module/algorithm/label.hpp
- cpp/label_module/label_module.cpp
- cpp/refactor_module/algorithm/refactor.cpp
- cpp/refactor_module/algorithm/refactor.hpp
- cpp/refactor_module/refactor_module.cpp
- e2e/label_test/test_exists_false/test.yml
- e2e/label_test/test_exists_not_node/test.yml
- e2e/label_test/test_exists_true/test.yml
- e2e/refactor_test/test_clone_subgraph_1/test.yml
- e2e/refactor_test/test_clone_subgraph_2/test.yml
- e2e/refactor_test/test_clone_subgraph_3/test.yml
- e2e_correctness/create_test/test_removeLabel_empty/test.yml
- e2e_correctness/create_test/test_removeLabel_exists/test.yml
- e2e_correctness/create_test/test_removeLabel_not_exists/test.yml
- e2e_correctness/refactor_test/test_clone_nodes1/test.yml
- e2e_correctness/refactor_test/test_clone_nodes2/test.yml
- e2e_correctness/refactor_test/test_clone_nodes3/test.yml
- e2e_correctness/refactor_test/test_clone_subgraph_path_1/test.yml
- e2e_correctness/refactor_test/test_clone_subgraph_path_2/test.yml
- e2e_correctness/refactor_test/test_clone_subgraph_path_3/test.yml
- e2e_correctness/refactor_test/test_invert1/test.yml
- e2e_correctness/refactor_test/test_invert2/test.yml
- e2e_correctness/refactor_test/test_invert3/test.yml
Change refactor, label and create procedures to fix GraphQL
> [E-GraphQL < T] Change procedures to fit GraphQL

- cpp/schema_module/algorithm/schema.cpp
- cpp/schema_module/algorithm/schema.hpp
- cpp/schema_module/schema_module.cpp
- e2e/schema_test/test_node_type_properties1/test.yml
- e2e/schema_test/test_node_type_properties2/test.yml
- e2e/schema_test/test_node_type_properties3/test.yml
- e2e/schema_test/test_rel_type_properties1/test.yml
- e2e/schema_test/test_rel_type_properties2/test.yml
- e2e/schema_test/test_rel_type_properties3/test.yml
> [E-graphQL < T - type-props] Fix type properties for graphQL

- cpp/refactor_module/algorithm/refactor.cpp
- cpp/refactor_module/algorithm/refactor.hpp
- e2e_correctness/refactor_test/test_clone_nodes1/test.yml
- e2e_correctness/refactor_test/test_clone_nodes2/test.yml
- e2e_correctness/refactor_test/test_clone_nodes3/test.yml
- e2e_correctness/refactor_test/test_clone_nodes4/input.cyp
- e2e_correctness/refactor_test/test_clone_nodes4/test.yml
Improve CloneNodes speed a bit and refactor the code a little.
> [E-refactor < T661] CloneNodesWithRelationships small refactor

- .github/workflows/test.yml
- .gitmodules
- e2e/collections_test/test_to_set1/test.yml
- e2e/collections_test/test_to_set2/test.yml
- e2e/collections_test/test_to_set3/test.yml
Switch tests to unofficial 2.12 version and fix/remove some flaky tests.
> [main < unofficial-build] Unofficial 2.12 build

- .github/workflows/test.yml
- cpp/refactor_module/algorithm/refactor.cpp
- cpp/refactor_module/algorithm/refactor.hpp
- cpp/refactor_module/refactor_module.cpp
- e2e_correctness/refactor_test/test_rename_type_1/input.cyp
- e2e_correctness/refactor_test/test_rename_type_1/test.yml
- e2e_correctness/refactor_test/test_rename_type_2/input.cyp
- e2e_correctness/refactor_test/test_rename_type_2/test.yml
- e2e_correctness/refactor_test/test_rename_type_3/input.cyp
- e2e_correctness/refactor_test/test_rename_type_3/test.yml
Implement refactor.rename_type
> [E-refactor < T380] Implement refactor.rename_type

- cpp/refactor_module/algorithm/refactor.cpp
> Fix refactor rvalue bind

- .github/workflows/docker_publish.yml
- add inputs for memgraph and mage version
- add choice of additional tag (latest or fix)
- add option to force push to dockerhub; overwrite existing image
- add option to shorten the version
> Modify docker_publish.yml

- .github/CODEOWNERS
- .github/pull_request_template.md
> Add new PR template

- .github/workflows/test.yml
- .github/workflows/test_no_ml.yml
This PR will make tests run on pushed rc tags. This change has already been made in `release/1.15` branch. However it hasn't been applied to `main`.
> Make tests run on pushed rc tags

- python/requirements.txt
- python/requirements_no_ml.txt
> Fix integration tests

- .github/workflows/package_mage.yaml
- .github/workflows/reusable_package_mage.yaml
- Dockerfile
- Dockerfile.cugraph
- Dockerfile.no_ML
- Dockerfile.release
- setup
This PR will change the build process in the following ways:
- we can now build in `RelWithDebInfo` mode
- debugging packages are installed in docker images
> Add support for RelWithDebInfo

- python/migrate.py
> Refactor python > migrate

- .github/workflows/release_artifacts.yaml
- .github/workflows/reusable_package_mage.yaml
This PR introduces a new workflow for publishing rc arifacts.
> Workflow for publishing RC artifacts

- .github/workflows/package_mage.yaml
- .github/workflows/release_artifacts.yaml
- .github/workflows/reusable_package_mage.yaml
This PR improves the initial workflow for creating releasable artifacts for all mage builds, which are the following:
- dev (dev + ML + RelWithDebInfo)
- prod (prod + ML + Release)
- relwithdebinfo (prod + ML + RelWithDebInfo)
- no-ml (prod + no ML + Release)
- no-ml-relwithdebinfo (prod + no ML + RelWithDebInfo)	
> Improve rc artifacts workflow

- .github/workflows/promote_rc_release.yaml
Fix syntax issues with promote rc to release workflow.
> Fix promote to release workflow

- .github/workflows/reusable_test.yml
- .github/workflows/test.yml
This PR adds support for S3 URI's when downloading memgraph binaries.
> Add support for S3 URI in test workflows

- .github/workflows/test.yml
This PR updates the memgraph binary version used in mage builds from 2.18.0 to 2.18.1
> Update memgraph binary from 2.18.0 to 2.18.1

- python/requirements.txt
Updated gensim version from 4.0.0 to 4.3.3
> Update gensim version

- .github/workflows/release_artifacts.yaml
- .github/workflows/test.yml
This PR fixes issues with links for memgraph binaries when running automated RC tests.
> Fix automated RC tests

- .github/workflows/test.yml
This PR fixes an unknown variable bug in the test workflow.
> Fix bug in test workflow

- .github/workflows/reusable_test.yml
- .github/workflows/test.yml
- e2e_correctness/conftest.py
- e2e_correctness/query_neo_mem.py
- e2e_correctness/test_modules.py
- python/link_prediction.py
- python/mage/link_prediction/link_prediction_util.py
- python/mage/link_prediction/predictors/DotPredictor.py
- python/mage/link_prediction/predictors/MLPPredictor.py
- python/node_classification.py
- python/pytest.ini
- run_e2e_correctness_tests.sh
- test_e2e_correctness.py
Instead of running unit tests on the host machine, run them inside docker container.
> Dockerize unit testing

- .github/workflows/package_mage.yaml
- .github/workflows/promote_rc_release.yaml
- .github/workflows/release_artifacts.yaml
- .github/workflows/reusable_package_mage.yaml
Additional docker image with `malloc` build of `memgraph/memgraph`.
> Add malloc release

- .github/workflows/promote_rc_release.yaml
- .github/workflows/release_artifacts.yaml
- .github/workflows/test.yml
Fix a few minor issues for release 3.1.1:
- Fix RC promote workflow to be able to correctly find `malloc` image
- Fix Boolean issue with release artifacts workflow
> Release 3.1.1 fixes

- Dockerfile.release
Added missing ODBC driver for SQL migrations to the docker image.
> Added missing ODBC driver for SQL

- .github/workflows/reusable_package_mage.yaml
- .github/workflows/reusable_smoke_tests.yml
- .github/workflows/reusable_test.yml
- Dockerfile.release
- Dockerfile.smoke
- scripts/test-mirrors.sh
> Use custom mirror inside CI

- Dockerfile.release
- python/requirements.txt
Upgrade torch version to 2.6 to address [this vulnerability](https://github.com/pytorch/pytorch/security/advisories/GHSA-53q9-r3pm-6pq6)
> Upgrade torch version to 2.6

- .github/workflows/build_rc.yml
- .github/workflows/release_artifacts.yaml
- .github/workflows/reusable_package_mage.yaml
- .github/workflows/reusable_test.yml
- .github/workflows/test.yml
Automate slightly more of the MAGE build by adding a new workflow that can be triggered by the Memgraph RC build.
> Increase RC build automation

- cpp/CMakeLists.txt
- cpp/math_module/CMakeLists.txt
- cpp/math_module/algorithm/math.cpp
- cpp/math_module/algorithm/math.hpp
- cpp/math_module/math_module.cpp
- e2e/math_test/test_ceiling_mode/test.yml
- e2e/math_test/test_default_args/test.yml
- e2e/math_test/test_down_mode/test.yml
- e2e/math_test/test_down_mode_negative/test.yml
- e2e/math_test/test_floor_mode/test.yml
- e2e/math_test/test_half_down_mode/test.yml
- e2e/math_test/test_half_even_mode/test.yml
- e2e/math_test/test_half_even_mode_odd/test.yml
- e2e/math_test/test_half_up_mode/test.yml
- e2e/math_test/test_unnecessary_mode/test.yml
- e2e/math_test/test_up_mode/test.yml
- e2e/math_test/test_up_mode_negative/test.yml
> Implement math.round

- e2e/json_util_test/test_from_json_list/test.yml
- e2e/json_util_test/test_to_json/test.yml
- python/mage/json_util/core.py
- python/tests/json_util/test_json_util.py
Fix json_util.to_json and json_util.from_json_list
> Fix json_util.to_json and json_util.from_json_list

- .github/workflows/pr_build.yml
- .github/workflows/reusable_package_mage.yaml
- scripts/pr_build_vars.py
New workflow to build MAGE after a PR has been merged into `master` in the `memgraph` repo.
> Add workflow to be triggered when PR gets merged in Memgraph
