- Dockerfile
Since Memgraph is in DockerHub now, this should be updated.
> Update Memgraph base docker image

- cpp/betweenness_centrality_module/betweenness_centrality_module.cpp
- e2e/betweenness_centrality_test/test_chain_directed/test.yml
- e2e/betweenness_centrality_test/test_chain_normalized/test.yml
- e2e/betweenness_centrality_test/test_chain_undirected/test.yml
- e2e/betweenness_centrality_test/test_complete_graph/test.yml
- e2e/betweenness_centrality_test/test_empty/test.yml
- e2e/betweenness_centrality_test/test_normalized_directed_graph/test.yml
- e2e/betweenness_centrality_test/test_two_nodes/test.yml
Return value was called `betweeenness_centrality` which has a typo
Closes #59
> Fix betweenness centrality algorithm name typo

- cpp/betweenness_centrality_module/betweenness_centrality_module.cpp
- cpp/mg_utility/mg_utils.hpp
- cpp/pagerank_module/pagerank_module.cpp
- cpp/pagerank_module/pagerank_online_module.cpp
Closes #96
`mg_utility` methods for inserting results follow the Insert{TYPE}ValueResult pattern, e.g. `InsertBoolValueResult`.
This PR renames `InsertDoubleValue` to ``InsertDoubleValueResult` to bring it in line with this.
> Clarify InsertDoubleValueResult inserts results

- cpp/mg_utility/mg_graph.hpp
Currently, ID validity checks in the C API never throw exceptions. This PR updates the check logic to cover both cases where inner IDs are invalid (under 0 / over N of nodes/edges).
> Fix ID validity check

- e2e/max_flow_test/test_path_recursive_return/input.cyp
- e2e/max_flow_test/test_path_recursive_return/test.yml
- python/max_flow.py
Recursive DFS used for finding flows in the Max Flow algorithm was failing when returning from a recursive call for multiple levels. `path = path[:-2]` simply reassigned the variable inside that function call, and didn't modify the list itself, leaving edges in path that shouldn't be there. `del path[-2:]` modifies the list at the original address, which is the wanted functionality.
#140 
> changed deletion of nodes from recursive dfs

- setup
The Rust dependency manager took a lot of memory and was failing for QEMU builds. The workaround is to enable git CLI dowload for external libraries.
> Fix Rust CI build

- e2e/graph_coloring_test/test_convergence_callback/test.yml
- e2e/graph_coloring_test/test_graph_init_algorithms/test.yml
- e2e/graph_coloring_test/test_graph_one_node/test.yml
- e2e/graph_coloring_test/test_graph_parallel/test.yml
- e2e/graph_coloring_test/test_graph_without_weight/test.yml
- e2e/graph_coloring_test/test_large_graph/test.yml
- e2e/graph_coloring_test/test_multiple_mutation/test.yml
- e2e/graph_coloring_test/test_random_mutation/test.yml
- python/graph_coloring.py
As was requested, outputs of Graph Coloring algorithm were changed from `vertex_id` and `string` representing color to `mgp.Vertex` and `int`
> Make Graph Coloring output vertices and integers instead of strings

- README.md
Our badge is showing an [issue](https://github.com/badges/shields/issues/8671) from Shields.io because they have changed the way of adding a badge for tests that are a part of a GitHub workflow. I changed the URL for the badge.
> Update test badge in README

- Dockerfile
- Dockerfile.release
- python/requirements.txt
Bump pytorch version up to 1.13.1+cu117 to avoid a critical PyTorch vulnerability ([Dependabot alert](https://github.com/advisories/GHSA-47fc-vmwq-366v)).
> [main < T333-MAGE] Bump pytorch version up

- cpp/node_module/algorithm/node.cpp
- cpp/node_module/algorithm/node.hpp
- cpp/node_module/node_module.cpp
- e2e/node_test/test_relationship_types_1/input.cyp
- e2e/node_test/test_relationship_types_1/test.yml
- e2e/node_test/test_relationship_types_2/input.cyp
- e2e/node_test/test_relationship_types_2/test.yml
- e2e/node_test/test_relationship_types_3/input.cyp
- e2e/node_test/test_relationship_types_3/test.yml
Implement node.relationship_types
> [E-node < T501] Implement node.relationship_types

- .github/workflows/test.yml
- rust/rsmgp-sys/src/temporal/tests.rs
The rust thread started panicking on two workflows for handling leap seconds. Check if it is a fluke or an error.
> [main < T] Fix rust failing tests

- setup
Libmgclient was getting copied into query modules but it was never intended to be used as a query module. 
[Issue 357](https://github.com/memgraph/mage/issues/357)
> [main < T676] Ignore libmgclient while copying query modules

- cpp/algo_module/algo_module.cpp
- cpp/algo_module/algorithm/algo.cpp
- cpp/algo_module/algorithm/algo.hpp
- e2e/algo_test/test_cover1/input.cyp
- e2e/algo_test/test_cover1/test.yml
- e2e/algo_test/test_cover2/input.cyp
- e2e/algo_test/test_cover2/test.yml
- e2e/algo_test/test_cover3/input.cyp
- e2e/algo_test/test_cover3/test.yml
> [E-algo < T581] Implement algo.cover

- cpp/path_module/algorithm/path.cpp
- cpp/path_module/algorithm/path.hpp
- cpp/path_module/path_module.cpp
- e2e/path_test/test_expand1/test.yml
- e2e/path_test/test_expand2/test.yml
- e2e/path_test/test_expand3/test.yml
- e2e/path_test/test_expand4/test.yml
- e2e/path_test/test_subgraph_all_1/test.yml
- e2e/path_test/test_subgraph_all_2/test.yml
- e2e/path_test/test_subgraph_all_3/test.yml
- e2e/path_test/test_subgraph_nodes_1/test.yml
- e2e/path_test/test_subgraph_nodes_2/test.yml
- e2e/path_test/test_subgraph_nodes_3/test.yml
Refactor the path module and change path subgraph to bfs instead of dfs which should improve the speed and lower memory usage by a lot
> [E-path < T667-T668] Path subgraph improvement and path refactor

- cpp/csv_utils_module/algorithm/csv_utils.cpp
Modifies the behavior of the `CreateCsvFile` procedure to not include a newline at the end of the line.
This behaviour is required by the Lab.
> Modify CreateCsvFile behavior to not include newline

- cpp/text_module/algorithm/text.cpp
- cpp/text_module/algorithm/text.hpp
- cpp/text_module/text_module.cpp
- e2e/text_test/test_regex_groups_1/test.yml
- e2e/text_test/test_regex_groups_2/test.yml
- e2e/text_test/test_regex_groups_3/test.yml
Added regex search based on neo4j apoc module.
Closes #412 
https://github.com/memgraph/mage/issues/412
> Regex search

- .github/workflows/package_mage.yaml
This PR creates a dummy package mage workflow.
This will be merged into master ASAP as a dummy workflow.
This is because manual execution isn't possible if a workflow doesn't exits on the default branch (`origin/main` in our case)
> Add dummy package_mage workflow

- python/equality_py.py
- python/migrate.py
- python/requirements.txt
- python/requirements_no_ml.txt
Postgresql migration module has been added.
X
- **Added a migration module from Postgres to Memgraph**
> Add postgresql migration

- setup
New query modules could not be built in Rust because there was a logical error in the code.
- **Fixed logical error when building new Rust query modules**
- **No PR needed**
> Fix building of newly created rust modules

- .github/workflows/test.yml
This PR fixes failing nightly runs of the Build and Test workflow. The memgraph_version input was invalid.
> Fix nightly build and test runs

- .github/workflows/reusable_package_mage.yaml
During the 2.18.1 release, the artifact names contained -rcX extension in both tar filename and image tag.
This PR fixes that
> Fix artifact names for release artifacts workflow

- python/mage/node2vec_online_module/w2v_learners.py
Since we updated gensim from 4.0.0 to 4.3.3 the newer version requires that in Word2Vec either `hs` or `negative` is positive and we had an edge case where both of these variables would end up non positive and would result in the module throwing.
> Node2vec - enforce that either negative_rate or hs are positive

- .gitmodules
.gitmodules was pointing to an old version of Memgraph main branch instead of the current latest release. This only affected local development since MAGE builds are created through CI which uses already prebuilt Memgraph. 
- **Fix gitmodules pointing to the wrong Memgraph commit when building MAGE locally.**
> Update .gitmodules to the latest Memgraph release

- .github/workflows/test.yml
Fix the link for memgraph package which is pulled for dev rc builds
> Fix which memgraph package is pulled for dev rc builds

- python/elastic_search_serialization.py
- python/graph_analyzer.py
- python/igraphalg.py
- python/link_prediction.py
- python/mage/graph_coloring_module/algorithms/meta_heuristics/quantum_annealing.py
- python/mage/graph_coloring_module/components/chain_chunk.py
- python/mage/graph_coloring_module/components/individual.py
- python/mage/graph_coloring_module/components/population.py
- python/mage/graph_coloring_module/iteration_callbacks/callback_actions/simple_tunneling.py
- python/mage/graph_coloring_module/utils/parameters_utils.py
- python/mage/node2vec/second_order_random_walk.py
- python/mage/node2vec_online_module/walk_sampling.py
- python/mage/node_classification/models/gatjk.py
- python/mage/node_classification/utils/extract_from_database.py
- python/mage/tgn/definitions/tgn.py
- python/mgp_igraph.py
- python/node_classification.py
- python/tests/graph_coloring/test_conflict_error.py
- python/tests/node2vec/test_basic_graph.py
- python/tests/node2vec_online/test_walk_sampling.py
- python/tgn.py
Run black on top of Python files.
> Run black on python folder

- .pre-commit-config.yaml
- python/mage/tgn/definitions/tgn.py
There was a different black version remote vs. locally. Added pre-commit hook which runs black and flake8 on python folder respecting configuration from pytest.ini
> Add pre-commit hook for black and flake8

- cpp/leiden_community_detection_module/algorithm/leiden.cpp
- cpp/leiden_community_detection_module/leiden_community_detection_module.cpp
- e2e/leiden_community_detection_test/test_empty/test.yml
When no communities are found in some cases, algorithm results in segfault. This PR provides fix for this case.
> Fix bug in Leiden when no communities are found

- .github/workflows/reusable_test.yml
- Dockerfile.release
Making query modules removed under v1.14.1 (text, link prediction, node classification) available again.
#471 
#470 
#469 
#448 
- **[Text, node classification and link prediction modules which were removed in v1.14.1 are brought back]**
> Bring back removed modules

- .github/workflows/reusable_test.yml
- Dockerfile
- Dockerfile.cugraph
- Dockerfile.no_ML
- Dockerfile.release
- cpp/CMakeLists.txt
- cpp/uuid_module/CMakeLists.txt
- cpp/uuid_module/uuid_module.cpp
- e2e/test_module.py
- e2e_correctness/test_modules.py
Old UUID module was relying on another github repo and was causing some build issues so it was changed to be the same as on Memgraph repo and use `uuid-dev` package.
- **uuid_generator uses a different method of generating UUIDs so it might not be compatible with the one in previous versions**
> Rewrite UUID module to be same as on Memgraph main repo

- README.md
- cpp/CMakeLists.txt
- cpp/refactor_module/algorithm/refactor.cpp
- cpp/refactor_module/algorithm/refactor.hpp
- e2e/test_module.py
- e2e_correctness/test_modules.py
EdgeSetTo, EdgeSetFrom and EdgeChangeType were removed from Memgraph and API in [PR2530](https://github.com/memgraph/memgraph/pull/2530) and some MAGE functions were using those functions so they were rewritten to not use them anymore.
BREAKING: `refactor.from`, `refactor.to`, `refactor.invert`, `refactor.delete_and_reconnect` and `refactor.rename_type` now create a new edge instead of modifying the old one. This causes changes if you relied on internal edge ID (previously it would stay the same now it changes due to creation of new edge). 
- **[`refactor.from`, `refactor.to`, `refactor.invert`, `refactor.delete_and_reconnect` and …
> Rewrite refactor modules to not use deleted API

- .github/workflows/promote_rc_release.yaml
An issue with the previous release was that we had to exclude some images from Docker Hub. The updated workflow should allow some images to be missing from the RC, but for the remaining images to be correctly handled.
[This action run](https://github.com/memgraph/mage/actions/runs/13903697454/job/38901458911) shows that this works. The two failures are unrelated to this problem (AWS permissions challenges!), but the remaining successful jobs manage to push and `arm` image without there also having to be an `amd` image; or in one case it "fails successfully" if there is nothing to upload - which is the point of this PR.
- Handle missing …
> refactor release promotion to allow for missing builds

- python/export_util.py
The export_util can fail if special characters are not supported by default OS encoding. Specifying the version should help because  `UTF-8` should work universally on multiple systems. 
Closes: #553 
- **Set UTF-8 encoding in the export utility to support special characters **
> Fix export_util.py to encode in the UTF-8 

- Dockerfile.no_ML
- Dockerfile.release
Minor change to set the user shell to /bin/bash for the memgraph user in line with previous releases.
> Set shell for memgraph user to /bin/bash

- .github/workflows/reusable_package_mage.yaml
- Dockerfile.no_ML
- Dockerfile.release
Modified dockerfiles to add a `debug` stage which installs `gdb` and the full MAGE repo within the image for the RelWithDebInfo build.
> Add gdb and full mage repo to relwithdebinfo image

- Dockerfile.release
Modified the Dockerfile such that the `HOME` directory for `memgraph` is now in `/home/memgraph` rather than `/var/lib/memgraph`. This should fix issues with missing Python modules when `/var/lib/memgraph` is mounted as an external volume. Fixes [#593](https://github.com/memgraph/mage/issues/593)
> Move memgraph user's home directory

- .github/workflows/daily_build.yml
Fixes daily build workflow by checking the correct GitHub variable name for `repository_dispatch` in order to use the `$payload` provided by the Memgraph daily build workflow.
> Fix event_name check

- .github/workflows/reusable_package_mage.yaml
The `reusable_package_mage.yaml` workflow is missing some steps which speed up the equivalent parts of `reusable_test.yaml` by using cache Python packages (this affects ARM significantly more than x86 builds). Should speed up packaging MAGE for ARM by about 30 minutes.
> Fix MAGE packaging workflow so it uses package cache

- .github/workflows/reusable_package_mage.yaml
- .github/workflows/reusable_test.yml
- scripts/verify_download_url.sh
Add a retry loop to the URL validity check in case the package isn't available yet.
> Fix memgraph package download from S3 flakiness

- .github/workflows/cve_scan.yml
- .github/workflows/daily_build.yml
- .github/workflows/manual_cve_scan.yml
- .github/workflows/promote_rc_release.yaml
- .github/workflows/release_artifacts.yaml
- .github/workflows/smoke_tests.yml
- .github/workflows/test.yml
Weekly CVE scan is blocked from running due to a conflict in the concurrency group name with the daily build workflow that triggers it. This fix should stop unrelated jobs from cancelling/conflicting with each other.
> Update workflow concurrency groups to avoid conflicts

- .github/pull_request_template.md
Stop tagging DX in PR template
> Stop tagging DX in PR template

- scripts/scan_languages.py
- scripts/triage.json
`cve-bin-tool` uses the `product`, `vendor` and `version` of a language package (e.g. `JMESpath` in this case) to check if there is a corresponding vulnerability within its database. The issue with this is that `JMESpath` has multiple packages for different languages, where their versions are not aligned and there is no differentiation between them in the CVE database. This means that the critical CVE which affects the Ruby version of `JMESpath` for versions `< 1.6.1` is flagged for the latest, unaffected Python package version `1.0.1`. The "solution" here is to triage that particular package so that it does not appear in the output of the CVE scanner.
> Fix CVE scan false positive

- scripts/cve_message.py
- scripts/scan_languages.py
CVE scan fails to upload the JSON file containing results of the `cve-bin-tool` language scan. This is likely due to the wrong path being passed for the `triage.json`.
> Fix artifact upload for CVE scan

- e2e/date_test/test_convert_format/test.yml
- python/date.py
GraphQL support needs `date.convert_format`, currently implemented in Memgraph's `query_modules`. When we build the Memgraph+MAGE image, MAGE's `date.py` overwrites Memgraph's. As there is no way to separate filename from the function's namespace, the best solution (for now) is to duplicate the code and tests here. When we combine both in a monorepo, the duplicated code can be removed.
> Implement duplicate `date.py` functions from Memgraph

- .github/workflows/update_cve_database.yml
`cve-bin-tool` fails to update it's database with open-source vulnerabilities due to a key error. I have fixed this in my personal fork of `cve-bin-tool`, so we can install that for now until the fix is made in a new release.
> fix: cve-bin-tool OSV update

- .github/workflows/cve_scan.yml
- .github/workflows/update_cve_database.yml
`cve-bin-tool` is a source of a lot of false positives and flakiness. Let's disable it for now, until their issues are fixed.
> Disable cve-bin-tool on weekly CVE scan
